import { expect, test, vi } from "vitest";
import { createProjectionConfigView } from "../../frontend/src/projection-config/config-view.js";
import { DEFAULT_PROJECTION_CONFIG } from "../../frontend/src/shared/projection-config-schema.js";
import { FIELD_DESCRIPTORS, NAMES_WALL_DESCRIPTORS } from "../../frontend/src/projection-config/config-controller.js";
import { createWarpEditor } from "../../frontend/src/projection-config/warp-editor.js";

test("view renders draggable node workspace and preserves an existing focused input", () => {
  const make = (tag = "div") => ({ tagName: tag.toUpperCase(), children: [], dataset: {}, style: {}, attributes: {}, classList: { toggle() {} }, appendChild(child) { this.children.push(child); child.parentElement = this; return child; }, append(...children) { children.forEach((child) => this.appendChild(child)); }, prepend(...children) { this.children.unshift(...children); }, remove() { if (this.parentElement) this.parentElement.children = this.parentElement.children.filter((child) => child !== this); }, setAttribute(key, value) { this.attributes[key] = value; }, removeAttribute(key) { delete this.attributes[key]; }, addEventListener(type, handler) { this.listeners ||= {}; (this.listeners[type] ||= []).push(handler); }, removeEventListener(type, handler) { this.listeners[type] = (this.listeners?.[type] || []).filter((entry) => entry !== handler); }, dispatch(type, event) { for (const handler of this.listeners?.[type] || []) handler({ currentTarget: this, target: this, ...event }); }, replaceChildren(...children) { this.children = children; } });
  const root = make("main");
  root.ownerDocument = { createElement: make, createElementNS: (_ns, tag) => make(tag), listeners: {}, addEventListener(type, handler) { (this.listeners[type] ||= []).push(handler); }, removeEventListener(type, handler) { this.listeners[type] = (this.listeners[type] || []).filter((item) => item !== handler); }, dispatch(type, event) { for (const handler of this.listeners[type] || []) handler(event); }, defaultView: { location: { origin: "http://localhost" }, addEventListener() {}, removeEventListener() {}, matchMedia: () => ({ matches: true, addEventListener() {}, removeEventListener() {} }) } };
  const onNode = vi.fn();
  const onOpenClockEditor = vi.fn();
  const onClockScene = vi.fn();
  const onClockElement = vi.fn();
  const onField = vi.fn();
  const onWarpPointer = vi.fn();
  const onWarpAction = vi.fn();
  const view = createProjectionConfigView(root, { descriptors: [...FIELD_DESCRIPTORS, ...NAMES_WALL_DESCRIPTORS], onAction() {}, onNode, onOpenClockEditor, onClockScene, onClockElement, onField, onWarpPointer, onWarpAction });
  const descendants = (node) => [node, ...(node.children || []).flatMap(descendants)];
  expect(descendants(root).filter((node) => node.tagName === "IFRAME")).toHaveLength(0);
  expect(descendants(root).filter((node) => node.dataset?.action === "warp-editor-open")).toHaveLength(4);
  expect(descendants(root).filter((node) => node.dataset?.action === "preview-expand")).toHaveLength(0);
  const labels = [];
  const walk = (node) => {
    if (!node) return;
    if (node.textContent) labels.push(node.textContent);
    for (const child of node.children || []) walk(child);
  };
  walk(root);
  expect(labels.join(" ")).toContain("Crop diagram");
  expect(labels.join(" ")).toContain("Drag headers to move nodes");
  expect(labels.join(" ")).toContain("Left inner-edge clearance");
  expect(labels.join(" ")).toContain("Right inner-edge clearance");
  expect([...view.nodeMap.keys()]).toEqual(["content", "names-wall", "clock-gis", "clock-projection", "pre", "left-crop", "right-crop", "left-fit", "right-fit", "left-keystone", "right-keystone", "left-grid", "right-grid", "left-output", "right-output"]);
  const gisClockNode = view.nodeMap.get("clock-gis");
  gisClockNode.dispatch("click");
  expect(onNode).toHaveBeenLastCalledWith("clock-gis");
  expect(onOpenClockEditor).not.toHaveBeenCalled();
  const gisScene = gisClockNode.children.find((node) => node.dataset?.action === "clock-scene");
  gisScene.value = "nova";
  gisScene.dispatch("change");
  expect(onClockScene).toHaveBeenCalledWith("nova");
  const projectionClockNode = view.nodeMap.get("clock-projection");
  const overlay = projectionClockNode.children.find((node) => node.dataset?.action === "clock-element");
  overlay.value = "legend";
  overlay.dispatch("change");
  expect(onClockElement).toHaveBeenCalledWith("legend");
  projectionClockNode.children.find((node) => node.dataset?.action === "clock-editor-open").dispatch("click");
  expect(onOpenClockEditor).toHaveBeenCalledWith("clock-projection");
  onOpenClockEditor.mockClear();
  gisClockNode.dispatch("dblclick");
  gisClockNode.dispatch("keydown", { key: "Enter", preventDefault() {} });
  expect(onOpenClockEditor.mock.calls).toEqual([["clock-gis"], ["clock-gis"]]);
  onOpenClockEditor.mockClear();
  const header = gisClockNode.children.find((node) => node.tagName === "H3");
  gisClockNode.dispatch("dblclick", { target: header });
  gisClockNode.dispatch("dblclick", { target: gisScene });
  gisClockNode.dispatch("keydown", { key: "Enter", target: gisScene });
  expect(onOpenClockEditor).not.toHaveBeenCalled();
  const nodeSelector = descendants(root).find((node) => node.className === "node-selector");
  const clockMobileOpen = descendants(root).find((node) => node.dataset?.action === "warp-editor-open-mobile");
  view.update({ state: { draft: structuredClone(DEFAULT_PROJECTION_CONFIG) }, selectedNode: "clock-gis", clockScene: "nova", clockElement: "legend" });
  expect(gisScene.value).toBe("nova");
  expect(view.controls.clockSceneInspector.value).toBe("nova");
  view.controls.clockSceneInspector.value = "timeline"; view.controls.clockSceneInspector.dispatch("change");
  expect(onClockScene).toHaveBeenLastCalledWith("timeline");
  view.update({ state: { draft: structuredClone(DEFAULT_PROJECTION_CONFIG) }, selectedNode: "clock-projection", clockScene: "nova", clockElement: "legend" });
  expect(overlay.value).toBe("legend");
  expect(view.controls.clockElementInspector.value).toBe("legend");
  view.update({ state: { draft: structuredClone(DEFAULT_PROJECTION_CONFIG) }, selectedNode: "clock-gis" });
  expect(clockMobileOpen.hidden).toBe(false);
  nodeSelector.value = "clock-gis"; clockMobileOpen.dispatch("click");
  expect(onOpenClockEditor).toHaveBeenCalledWith("clock-gis");
  onNode.mockClear();
  const graphColumn = root.children[0].children.find((node) => node.tagName === "DIV" && node.className === "config-workspace").children[0];
  const inspector = root.children[0].children.find((node) => node.className === "config-workspace").children[1];
  expect(inspector.open).toBe(true);
  const viewport = graphColumn.children.find((node) => node.className === "node-graph-viewport");
  expect(viewport.className).toBe("node-graph-viewport");
  const graphSvg = viewport.children.find((node) => node.className === "node-graph").children[0];
  expect(Number(graphSvg.attributes.viewBox.split(" ")[2])).toBeGreaterThan(1500);
  expect(graphSvg.children[0].attributes["vector-effect"]).toBe("non-scaling-stroke");
  expect(view.nodeMap.get("pre").children.some((node) => node.dataset?.port === "in")).toBe(true);
  expect(view.nodeMap.get("names-wall").children.some((node) => node.dataset?.port === "in" || node.dataset?.port === "out")).toBe(false);
  expect(view.nodeMap.get("names-wall").children.some((node) => node.className === "names-wall-status")).toBe(true);
  const namesDraft = structuredClone(DEFAULT_PROJECTION_CONFIG);
  view.update({ state: { draft: namesDraft }, selectedNode: "names-wall", namesWallStatus: { state: "auto-reduced", requestedFontPx: 12, effectiveFontPx: 9, minimumFontPx: 8, expected: 1228, placed: 1228 } });
  const closeness = view.fields.get("names-wall:namesWall.inwardShiftPercent");
  expect(closeness.wrap.hidden).toBe(false);
  expect(closeness.value.parentElement).toBe(closeness.range.parentElement);
  closeness.range.value = "50";
  closeness.range.dispatch("input");
  expect(closeness.value.textContent).toBe("50");
  expect(onField).not.toHaveBeenCalledWith("namesWall.inwardShiftPercent", "50", "range");
  closeness.range.dispatch("change");
  expect(onField).toHaveBeenCalledWith("namesWall.inwardShiftPercent", "50", "range");
  onField.mockClear();
  const resetPages = view.nodeMap.get("names-wall").children.find((node) => node.dataset?.action === "reset-page-spacing");
  expect(resetPages.hidden).toBe(false);
  resetPages.dispatch("click");
  expect(onField).toHaveBeenCalledWith("namesWall.inwardShiftPercent", "0", "number");
  onField.mockClear();
  const wallStatus = view.nodeMap.get("names-wall").children.find((node) => node.className === "names-wall-status");
  expect(wallStatus.textContent).toContain("Auto-reduced");
  expect(wallStatus.textContent).toContain("using 9 px");
  namesDraft.namesWall.activeMode = "model";
  view.update({ state: { draft: namesDraft }, selectedNode: "names-wall" });
  expect(closeness.wrap.hidden).toBe(true);
  expect(resetPages.hidden).toBe(true);
  const draft = JSON.parse(JSON.stringify(DEFAULT_PROJECTION_CONFIG));
  draft.outputs.right.crop.x0 = 0.4;
  draft.outputs.right.post.tx = 2;
  view.update({ state: { draft } });
  expect(descendants(root).filter((node) => node.tagName === "IFRAME")).toHaveLength(0);
  expect(Number(view.controls.cropSvg.rightRect.attributes.x)).toBeCloseTo(40.8);
  expect(view.controls.cropSvg.leftVisibleRect.hidden).toBe(false);
  expect(view.controls.cropSvg.rightVisibleRect.hidden).toBe(true);
  const warpEditor = createWarpEditor({ config: draft, output: "left" });
  inspector.open = false;
  view.update({ state: { draft }, selectedNode: "left-keystone", warpStates: { left: { ...warpEditor.getState(), config: warpEditor.getConfig(), handles: warpEditor.getControlPoints() } } });
  expect(inspector.open).toBe(true);
  expect(view.controls.warpPanel.hidden).toBe(false);
  expect(view.controls.warpEnabled.attributes["aria-label"]).toBe("Enable browser warp");
  expect(view.controls.warpSurface.children.length).toBe(6);
  expect(view.controls.warpStep.parentElement.className).toBe("warp-fine-primary");
  expect(view.controls.warpArrows.parentElement.className).toBe("warp-fine-primary");
  expect(view.controls.warpActions.parentElement.className).toBe("warp-fine-secondary");
  view.update({ state: { draft }, selectedNode: "left-keystone", warpStates: { left: { ...warpEditor.getState(), config: warpEditor.getConfig(), handles: [{ x: -0.05, y: -0.1 }, { x: 1.05, y: -0.1 }, { x: -0.05, y: 1.1 }, { x: 1.05, y: 1.1 }] } } });
  const fittedViewBox = view.controls.warpSurface.attributes.viewBox.split(" ").map(Number);
  expect(fittedViewBox[0]).toBeLessThan(0);
  expect(fittedViewBox[2]).toBeGreaterThan(1920);
  draft.outputs.right.warp.baseline = { type: "identity", width: 1920, height: 1080, origin: "top-left" };
  const rightIdentityWarpEditor = createWarpEditor({ config: draft, output: "right" });
  rightIdentityWarpEditor.setMode("grid");
  view.update({ state: { draft }, selectedNode: "right-grid", warpStates: { right: { ...rightIdentityWarpEditor.getState(), config: rightIdentityWarpEditor.getConfig(), handles: rightIdentityWarpEditor.getControlPoints() } } });
  expect(view.controls.warpMode.value).toBe("grid");
  expect(view.controls.warpSelection.children.at(-1).tagName).toBe("SELECT");
  expect(view.controls.warpSelection.children.at(-1).children.length).toBeGreaterThan(56);
  expect(view.controls.warpSurface.children.some((node) => node.attributes.class === "warp-grid-line")).toBe(true);
  view.controls.warpSurface.dispatch("pointerdown", { button: 0, pointerId: 1, clientX: 40, clientY: 40 });
  expect(onWarpPointer).not.toHaveBeenCalled();
  expect(view.cancelWarpPointer).toBeTypeOf("function");
  root.ownerDocument.dispatch("keydown", { key: "ArrowRight", target: view.controls.warpSurface, preventDefault: vi.fn() });
  expect(onWarpAction).not.toHaveBeenCalledWith("warp-nudge", expect.anything());
  const focused = view.fields.get("inspector:pre.tx").number;
  focused.value = "1.";
  root.ownerDocument.activeElement = focused;
  draft.pre.tx = 0.02;
  view.update({ state: { draft } });
  expect(focused.value).toBe("1.");
  focused.value = "-";
  view.update({ state: { draft } });
  expect(focused.value).toBe("-");
  expect(view.fields.get("pre:pre.tx").range.value).toBe("2.00");
  const inline = view.fields.get("pre:pre.tx").number;
  const inlineRow = view.fields.get("pre:pre.tx").wrap.children.find((node) => node.className === "config-field-row");
  expect(inlineRow.children.at(-1).attributes["aria-label"]).toContain("Increase Base-view X offset");
  expect(inlineRow.children.at(-1).title).toContain("0.01%");
  inline.blur = () => inline.dispatch("blur", {});
  inline.value = "0.";
  inline.dispatch("keydown", { key: "Enter", preventDefault: vi.fn() });
  expect(onField).toHaveBeenCalledTimes(1);
  expect(onField).toHaveBeenCalledWith("pre.tx", "0.", "number");
  const fitCard = view.nodeMap.get("right-fit");
  const preventDefault = vi.fn();
  fitCard.dispatch("keydown", { key: "Enter", preventDefault });
  fitCard.dispatch("keydown", { key: " ", preventDefault });
  expect(onNode).toHaveBeenCalledTimes(2);
  expect(onNode).toHaveBeenLastCalledWith("right-fit");
  fitCard.dispatch("keydown", { key: " ", target: view.fields.get("right-fit:outputs.right.post.scale").range, preventDefault });
  expect(onNode).toHaveBeenCalledTimes(2);
  const openGrid = view.nodeMap.get("right-grid").children.find((node) => node.dataset?.action === "warp-editor-open");
  view.update({ state: { draft }, selectedNode: "right-grid", warpStates: { right: { ...rightIdentityWarpEditor.getState(), config: rightIdentityWarpEditor.getConfig(), handles: rightIdentityWarpEditor.getControlPoints() } } });
  openGrid.dispatch("click");
  expect(onNode).toHaveBeenLastCalledWith("right-grid");
  expect(descendants(root).filter((node) => node.tagName === "IFRAME")).toHaveLength(1);
  root.ownerDocument.dispatch("keydown", { key: "ArrowRight", target: view.controls.warpSurface, shiftKey: true, preventDefault: vi.fn() });
  expect(onWarpAction).toHaveBeenCalledWith("warp-nudge", { direction: "right", coarse: true, fine: false });
  onWarpAction.mockClear();
  for (const [key, direction] of [["ArrowUp", "up"], ["ArrowDown", "down"], ["ArrowLeft", "left"], ["ArrowRight", "right"]]) {
    root.ownerDocument.dispatch("keydown", { key, target: view.controls.warpSurface, preventDefault: vi.fn() });
    expect(onWarpAction).toHaveBeenLastCalledWith("warp-nudge", { direction, coarse: false, fine: false });
  }
  root.ownerDocument.dispatch("keydown", { key: "ArrowUp", target: view.controls.warpSurface, altKey: true, preventDefault: vi.fn() });
  expect(onWarpAction).toHaveBeenLastCalledWith("warp-nudge", { direction: "up", coarse: false, fine: true });
  root.ownerDocument.dispatch("keydown", { key: "ArrowDown", target: view.controls.warpSurface, shiftKey: true, altKey: true, preventDefault: vi.fn() });
  expect(onWarpAction).toHaveBeenLastCalledWith("warp-nudge", { direction: "down", coarse: true, fine: true });
  onWarpAction.mockClear();
  view.controls.warpSurface.focus = vi.fn();
  const rightArrow = descendants(root).find((node) => node.dataset?.action === "warp-nudge" && node.dataset?.direction === "right");
  rightArrow.dispatch("click", { detail: 1 });
  expect(onWarpAction).toHaveBeenCalledTimes(1);
  expect(onWarpAction).toHaveBeenCalledWith("warp-nudge", { direction: "right" });
  expect(view.controls.warpSurface.focus).toHaveBeenCalledOnce();
  onWarpAction.mockClear();
  root.ownerDocument.dispatch("keydown", { key: "ArrowLeft", target: view.controls.warpPositionX, preventDefault: vi.fn() });
  root.ownerDocument.dispatch("keydown", { key: "ArrowLeft", target: root, preventDefault: vi.fn() });
  expect(onWarpAction).not.toHaveBeenCalled();
  descendants(root).find((node) => node.dataset?.action === "warp-editor-close").dispatch("click");
  expect(descendants(root).filter((node) => node.tagName === "IFRAME")).toHaveLength(0);
  root.ownerDocument.dispatch("keydown", { key: "ArrowRight", target: view.controls.warpSurface, preventDefault: vi.fn() });
  expect(onWarpAction).not.toHaveBeenCalled();
  view.update({ state: { draft }, selectedNode: "right-grid", warpStates: { right: { ...rightIdentityWarpEditor.getState(), config: rightIdentityWarpEditor.getConfig(), handles: rightIdentityWarpEditor.getControlPoints() } } });
  const mobileOpen = descendants(root).find((node) => node.dataset?.action === "warp-editor-open-mobile");
  expect(mobileOpen.hidden).toBe(false);
  mobileOpen.dispatch("click");
  expect(descendants(root).filter((node) => node.tagName === "IFRAME")).toHaveLength(1);
  expect(descendants(root).find((node) => node.tagName === "IFRAME").src).toContain("span=right");
  descendants(root).find((node) => node.dataset?.action === "warp-editor-close").dispatch("click");
  expect(descendants(root).filter((node) => node.tagName === "IFRAME")).toHaveLength(0);
  expect(view.dispose).toBeTypeOf("function");
  view.dispose();
});

test("Names wall keeps controls editable while showing pending and incomplete candidates", () => {
  const make = (tag = "div") => ({ tagName: tag.toUpperCase(), children: [], dataset: {}, style: {}, attributes: {}, classList: { toggle() {} }, appendChild(child) { this.children.push(child); child.parentElement = this; return child; }, append(...children) { children.forEach((child) => this.appendChild(child)); }, prepend(...children) { this.children.unshift(...children); }, remove() {}, setAttribute(key, value) { this.attributes[key] = value; }, addEventListener(type, handler) { this.listeners ||= {}; (this.listeners[type] ||= []).push(handler); }, removeEventListener() {}, replaceChildren(...children) { this.children = children; } });
  const root = make("main");
  root.ownerDocument = { createElement: make, createElementNS: (_ns, tag) => make(tag), defaultView: { location: { origin: "http://localhost" }, addEventListener() {}, removeEventListener() {}, matchMedia: () => ({ matches: false, addEventListener() {}, removeEventListener() {} }) } };
  const view = createProjectionConfigView(root, { descriptors: [...FIELD_DESCRIPTORS, ...NAMES_WALL_DESCRIPTORS], onField() {}, onNamesMode() {} });
  const draft = structuredClone(DEFAULT_PROJECTION_CONFIG);
  view.update({ state: { draft }, selectedNode: "names-wall", namesWallStatus: { state: "building", requestedFontPx: 12, minimumFontPx: 8, expected: null, placed: null } });
  const control = view.fields.get("names-wall:namesWall.requestedFontPx");
  expect(control.number.disabled).not.toBe(true);
  expect(view.nodeMap.get("names-wall").children.find((node) => node.className === "names-wall-status").dataset.state).toBe("building");
  view.update({ state: { draft, snapshot: { config: structuredClone(draft) } }, selectedNode: "names-wall", namesWallStatus: { state: "invalid", requestedFontPx: 6, minimumFontPx: 6, expected: 1228, placed: 1201, reason: "invalid Tkuma ring" } });
  const status = view.nodeMap.get("names-wall").children.find((node) => node.className === "names-wall-status");
  expect(status.textContent).toContain("1201 of 1228");
  expect(status.textContent).toContain("effective none");
  expect(status.textContent).toContain("Saved calibration cannot display a complete names wall");
  expect(status.textContent).not.toContain("cannot fit");
  expect(status.textContent).not.toContain("Draft is unsaved");
  view.update({ state: { draft, snapshot: { config: structuredClone(draft) }, hasLocalDraft: true }, selectedNode: "names-wall", namesWallStatus: { state: "invalid", requestedFontPx: 6, minimumFontPx: 6, expected: 1228, placed: 1201, reason: "capacity at minimum" } });
  expect(status.textContent).toContain("Draft is unsaved");
  expect(status.textContent).toContain("output state is unconfirmed");
  expect(status.textContent).not.toContain("last complete wall");
  expect(status.title).toContain("reference-plane pixels");
  expect(control.number.disabled).not.toBe(true);
  view.dispose();
});

test("repeated refresh keeps inspector fields scoped to the selected node", () => {
  const make = (tag = "div") => ({ tagName: tag.toUpperCase(), children: [], dataset: {}, style: {}, attributes: {}, classList: { toggle() {} }, appendChild(child) { this.children.push(child); child.parentElement = this; return child; }, append(...children) { children.forEach((child) => this.appendChild(child)); }, prepend(...children) { this.children.unshift(...children); }, remove() {}, setAttribute(key, value) { this.attributes[key] = value; }, removeAttribute(key) { delete this.attributes[key]; }, addEventListener(type, handler) { this.listeners ||= {}; (this.listeners[type] ||= []).push(handler); }, removeEventListener() {}, dispatch(type, event) { for (const handler of this.listeners?.[type] || []) handler({ currentTarget: this, target: this, ...event }); }, replaceChildren(...children) { this.children = children; } });
  const root = make("main"); root.ownerDocument = { createElement: make, createElementNS: (_ns, tag) => make(tag), defaultView: { matchMedia: () => ({ matches: false }) } };
  const view = createProjectionConfigView(root, { descriptors: [...FIELD_DESCRIPTORS, ...NAMES_WALL_DESCRIPTORS] });
  const draft = structuredClone(DEFAULT_PROJECTION_CONFIG);
  for (let n = 0; n < 3; n += 1) view.update({ state: { draft }, selectedNode: "right-fit" });
  expect(view.fields.get("inspector:outputs.right.post.scale").wrap.hidden).toBe(false);
  expect(view.fields.get("inspector:outputs.right.post.tx").wrap.hidden).toBe(false);
  expect(view.fields.get("inspector:outputs.right.post.ty").wrap.hidden).toBe(false);
  expect(view.fields.get("inspector:pre.scale").wrap.hidden).toBe(true);
  expect(view.fields.get("inspector:outputs.right.crop.x0").wrap.hidden).toBe(true);
  expect(view.fields.get("inspector:namesWall.requestedFontPx").wrap.hidden).toBe(true);
  draft.namesWall.activeMode = "model";
  view.update({ state: { draft }, selectedNode: "names-wall" });
  expect(view.fields.get("inspector:namesWall.requestedFontPx").wrap.hidden).toBe(false);
  expect(view.fields.get("inspector:namesWall.inwardShiftPercent").wrap.hidden).toBe(true);
  expect(view.fields.get("inspector:namesWall.innerEdgeInsetPx.left").wrap.hidden).toBe(false);
  const editor = createWarpEditor({ config: draft, output: "right" });
  view.update({ state: { draft }, selectedNode: "right-grid", warpStates: { right: { ...editor.getState(), config: editor.getConfig(), handles: editor.getControlPoints() } } });
  expect(view.controls.warpPanel.hidden).toBe(false);
  expect(view.fields.get("inspector:outputs.right.post.scale").wrap.hidden).toBe(true);
  view.dispose();
});

test("invalid warp coordinates preserve handles and show an accessible error", () => {
  const make = (tag = "div") => ({ tagName: tag.toUpperCase(), children: [], dataset: {}, style: {}, attributes: {}, classList: { toggle() {} }, appendChild(child) { this.children.push(child); child.parentElement = this; return child; }, append(...children) { children.forEach((child) => this.appendChild(child)); }, prepend(...children) { this.children.unshift(...children); }, remove() {}, setAttribute(key, value) { this.attributes[key] = value; }, removeAttribute(key) { delete this.attributes[key]; }, addEventListener(type, handler) { this.listeners ||= {}; (this.listeners[type] ||= []).push(handler); }, removeEventListener() {}, dispatch(type, event) { for (const handler of this.listeners?.[type] || []) handler({ currentTarget: this, target: this, ...event }); }, replaceChildren(...children) { this.children = children; } });
  const root = make("main"); root.ownerDocument = { createElement: make, createElementNS: (_ns, tag) => make(tag), defaultView: { matchMedia: () => ({ matches: false }) } };
  const onWarpAction = vi.fn();
  const view = createProjectionConfigView(root, { descriptors: FIELD_DESCRIPTORS, onWarpAction });
  const draft = structuredClone(DEFAULT_PROJECTION_CONFIG); const editor = createWarpEditor({ config: draft, output: "left" });
  const handles = editor.getControlPoints();
  view.update({ state: { draft }, selectedNode: "left-keystone", warpStates: { left: { ...editor.getState(), config: editor.getConfig(), handles } } });
  for (const [input, axis] of [[view.controls.warpPositionX, "x"], [view.controls.warpPositionY, "y"]]) {
    input.value = ""; input.dispatch("change");
    expect(input.attributes["aria-invalid"]).toBe("true");
    expect(view.controls.warpNumeric.children.find((node) => node.id === `warp-position-${axis}-error`).textContent).toContain("Enter a finite coordinate");
    input.value = "-"; input.dispatch("change");
    expect(input.attributes["aria-invalid"]).toBe("true");
    expect(handles).toEqual(editor.getControlPoints());
  }
  expect(onWarpAction).not.toHaveBeenCalled();
  view.controls.warpPositionX.value = "-12.5"; view.controls.warpPositionX.dispatch("change");
  expect(onWarpAction).toHaveBeenCalledWith("warp-set-position", { axis: "x", pixels: -12.5 });
  expect(view.controls.warpPositionX.attributes["aria-invalid"]).toBeUndefined();
  view.controls.warpPositionY.value = "-4.25"; view.controls.warpPositionY.dispatch("change");
  expect(onWarpAction).toHaveBeenCalledWith("warp-set-position", { axis: "y", pixels: -4.25 });
  expect(onWarpAction).toHaveBeenCalledTimes(2);
  expect(view.controls.warpPositionY.attributes["aria-invalid"]).toBeUndefined();
  view.dispose();
});

test("selection refresh clears a stale warp error when it replaces the unfocused coordinate", () => {
  const make = (tag = "div") => ({ tagName: tag.toUpperCase(), children: [], dataset: {}, style: {}, attributes: {}, classList: { toggle() {} }, appendChild(child) { this.children.push(child); child.parentElement = this; return child; }, append(...children) { children.forEach((child) => this.appendChild(child)); }, prepend(...children) { this.children.unshift(...children); }, remove() {}, setAttribute(key, value) { this.attributes[key] = value; }, removeAttribute(key) { delete this.attributes[key]; }, addEventListener(type, handler) { this.listeners ||= {}; (this.listeners[type] ||= []).push(handler); }, removeEventListener() {}, dispatch(type, event) { for (const handler of this.listeners?.[type] || []) handler({ currentTarget: this, target: this, ...event }); }, replaceChildren(...children) { this.children = children; } });
  const root = make("main"); const doc = { activeElement: null, createElement: make, createElementNS: (_ns, tag) => make(tag), defaultView: { matchMedia: () => ({ matches: false }) } }; root.ownerDocument = doc;
  const onWarpAction = vi.fn(); const view = createProjectionConfigView(root, { descriptors: FIELD_DESCRIPTORS, onWarpAction });
  const draft = structuredClone(DEFAULT_PROJECTION_CONFIG); const editor = createWarpEditor({ config: draft, output: "left" });
  const warpStates = { left: { ...editor.getState(), config: editor.getConfig(), handles: editor.getControlPoints() } };
  view.update({ state: { draft }, selectedNode: "left-keystone", warpStates });
  view.controls.warpPositionX.value = ""; view.controls.warpPositionX.dispatch("change");
  expect(view.controls.warpPositionX.attributes["aria-invalid"]).toBe("true");
  editor.select({ kind: "corner", index: 1 });
  view.update({ state: { draft }, selectedNode: "left-keystone", warpStates: { left: { ...editor.getState(), config: editor.getConfig(), handles: editor.getControlPoints() } } });
  expect(view.controls.warpPositionX.attributes["aria-invalid"]).toBeUndefined();
  expect(view.controls.warpNumeric.children.find((node) => node.id === "warp-position-x-error").textContent).toBe("");
  expect(onWarpAction).not.toHaveBeenCalled();
  view.dispose();
});
