import { expect, test, vi } from "vitest";
import { createProjectionConfigView } from "../../frontend/src/projection-config/config-view.js";
import { DEFAULT_PROJECTION_CONFIG } from "../../frontend/src/shared/projection-config-schema.js";
import { FIELD_DESCRIPTORS } from "../../frontend/src/projection-config/config-controller.js";

test("view renders draggable node workspace and preserves an existing focused input", () => {
  const make = (tag = "div") => ({ tagName: tag.toUpperCase(), children: [], dataset: {}, style: {}, attributes: {}, classList: { toggle() {} }, appendChild(child) { this.children.push(child); child.parentElement = this; return child; }, append(...children) { children.forEach((child) => this.appendChild(child)); }, prepend(...children) { this.children.unshift(...children); }, remove() { if (this.parentElement) this.parentElement.children = this.parentElement.children.filter((child) => child !== this); }, setAttribute(key, value) { this.attributes[key] = value; }, removeAttribute(key) { delete this.attributes[key]; }, addEventListener(type, handler) { this.listeners ||= {}; (this.listeners[type] ||= []).push(handler); }, removeEventListener(type, handler) { this.listeners[type] = (this.listeners?.[type] || []).filter((entry) => entry !== handler); }, dispatch(type, event) { for (const handler of this.listeners?.[type] || []) handler({ currentTarget: this, target: this, ...event }); }, replaceChildren(...children) { this.children = children; } });
  const root = make("main");
  root.ownerDocument = { createElement: make, createElementNS: (_ns, tag) => make(tag), defaultView: { matchMedia: () => ({ matches: true, addEventListener() {}, removeEventListener() {} }) } };
  const onNode = vi.fn();
  const onField = vi.fn();
  const view = createProjectionConfigView(root, { descriptors: FIELD_DESCRIPTORS, onAction() {}, onNode, onField });
  const labels = [];
  const walk = (node) => {
    if (!node) return;
    if (node.textContent) labels.push(node.textContent);
    for (const child of node.children || []) walk(child);
  };
  walk(root);
  expect(labels.join(" ")).toContain("Crop diagram");
  expect(labels.join(" ")).toContain("Drag headers to move nodes");
  expect([...view.nodeMap.keys()]).toEqual(["content", "pre", "left-crop", "right-crop", "left-fit", "right-fit", "left-output", "right-output"]);
  const graphColumn = root.children[0].children.find((node) => node.tagName === "DIV" && node.className === "config-workspace").children[0];
  const inspector = root.children[0].children.find((node) => node.className === "config-workspace").children[1];
  expect(inspector.open).toBe(true);
  const viewport = graphColumn.children.find((node) => node.className === "node-graph-viewport");
  expect(viewport.className).toBe("node-graph-viewport");
  const graphSvg = viewport.children.find((node) => node.className === "node-graph").children[0];
  expect(Number(graphSvg.attributes.viewBox.split(" ")[2])).toBeGreaterThan(1500);
  expect(graphSvg.children[0].attributes["vector-effect"]).toBe("non-scaling-stroke");
  expect(view.nodeMap.get("pre").children.some((node) => node.dataset?.port === "in")).toBe(true);
  const draft = JSON.parse(JSON.stringify(DEFAULT_PROJECTION_CONFIG));
  draft.outputs.right.crop.x0 = 0.4;
  draft.outputs.right.post.tx = 2;
  view.update({ state: { draft } });
  expect(Number(view.controls.cropSvg.rightRect.attributes.x)).toBeCloseTo(40.8);
  expect(view.controls.cropSvg.leftVisibleRect.hidden).toBe(false);
  expect(view.controls.cropSvg.rightVisibleRect.hidden).toBe(true);
  const focused = view.fields.get("inspector:pre.tx").number;
  focused.value = "1.";
  root.ownerDocument.activeElement = focused;
  draft.pre.tx = 0.02;
  view.update({ state: { draft } });
  expect(focused.value).toBe("1.");
  focused.value = "-";
  view.update({ state: { draft } });
  expect(focused.value).toBe("-");
  expect(view.fields.get("pre:pre.tx").range.value).toBe("2.00");
  const inline = view.fields.get("pre:pre.tx").number;
  const inlineRow = view.fields.get("pre:pre.tx").wrap.children.find((node) => node.className === "config-field-row");
  expect(inlineRow.children.at(-1).attributes["aria-label"]).toContain("Increase Base-view X offset");
  expect(inlineRow.children.at(-1).title).toContain("0.01%");
  inline.blur = () => inline.dispatch("blur", {});
  inline.value = "0.";
  inline.dispatch("keydown", { key: "Enter", preventDefault: vi.fn() });
  expect(onField).toHaveBeenCalledTimes(1);
  expect(onField).toHaveBeenCalledWith("pre.tx", "0.", "number");
  const fitCard = view.nodeMap.get("right-fit");
  const preventDefault = vi.fn();
  fitCard.dispatch("keydown", { key: "Enter", preventDefault });
  fitCard.dispatch("keydown", { key: " ", preventDefault });
  expect(onNode).toHaveBeenCalledTimes(2);
  expect(onNode).toHaveBeenLastCalledWith("right-fit");
  fitCard.dispatch("keydown", { key: " ", target: view.fields.get("right-fit:outputs.right.post.scale").range, preventDefault });
  expect(onNode).toHaveBeenCalledTimes(2);
  expect(view.dispose).toBeTypeOf("function");
  view.dispose();
});
