repositories:
  - name: nur-io
    url: https://github.com/your-org/nur-io.git
    branch: master
  - name: nur-remote-controller
    url: https://github.com/your-org/nur-remote-controller.git
    branch: master
  - name: nur-front
    url: https://github.com/your-org/nur-front.git
    branch: master
  - name: nur-projection
    url: https://github.com/your-org/nur-projection.git
    branch: master