# Generated by Django 4.2.27 on 2026-01-10 08:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_delete_maptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Internal name (e.g., 'otef', 'idistrict')", max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable display name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the table/data source', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this table is currently active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='indicator',
            name='table',
            field=models.ForeignKey(blank=True, help_text='The table/data source this indicator belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='backend.table'),
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('table', 'indicator_id')},
        ),
        migrations.AddIndex(
            model_name='indicator',
            index=models.Index(fields=['table', 'indicator_id'], name='backend_ind_table_i_1c5688_idx'),
        ),
    ]
