# Generated by Django 4.2.21 on 2026-01-01 13:54

import backend.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_delete_maptype'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUpload',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=backend.models.user_upload_path)),
                ('display_name', models.CharField(default='', max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
