# Generated by Django 4.2.21 on 2026-01-03 07:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_userupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUploadCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'User Upload Categories',
                'ordering': ['-is_default', 'display_name'],
            },
        ),
        migrations.AddField(
            model_name='userupload',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='backend.useruploadcategory'),
        ),
    ]
