# Generated by Django 4.2.27 on 2026-01-17 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_add_ugc_support_and_media_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTEFViewportState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viewport', models.JSONField(default=dict)),
                ('layers', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otef_viewport', to='backend.table')),
            ],
        ),
        migrations.CreateModel(
            name='OTEFModelConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_bounds', models.JSONField(default=dict)),
                ('model_image', models.FileField(blank=True, null=True, upload_to='otef/models/')),
                ('model_image_transparent', models.FileField(blank=True, null=True, upload_to='otef/models/')),
                ('calibration_data', models.JSONField(default=dict)),
                ('coordinate_system', models.CharField(default='EPSG:2039', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otef_config', to='backend.table')),
            ],
        ),
        migrations.CreateModel(
            name='GISLayer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('layer_type', models.CharField(choices=[('geojson', 'GeoJSON'), ('vector_tiles', 'Vector Tiles'), ('raster', 'Raster')], default='geojson', max_length=50)),
                ('data', models.JSONField(default=dict)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('style_config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gis_layers', to='backend.table')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('table', 'name')},
            },
        ),
    ]
