# Generated by Django 4.2.27 on 2026-02-15 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_otefviewportstate_otefmodelconfig_gislayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='otefviewportstate',
            name='animations',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='otefviewportstate',
            name='bounds_polygon',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='LayerState',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('layer_id', models.CharField(help_text='Full layer ID: group_id.layer_id', max_length=200)),
                ('enabled', models.BooleanField(default=False, help_text='Whether this specific layer is visible')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_states', to='backend.table')),
            ],
            options={
                'ordering': ['layer_id'],
                'indexes': [models.Index(fields=['table', 'layer_id'], name='backend_lay_table_i_863e01_idx')],
                'unique_together': {('table', 'layer_id')},
            },
        ),
        migrations.CreateModel(
            name='LayerGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.CharField(help_text="Layer pack ID (e.g., 'map_3_future', '_legacy')", max_length=100)),
                ('enabled', models.BooleanField(default=False, help_text='Whether the entire group is enabled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layer_groups', to='backend.table')),
            ],
            options={
                'ordering': ['group_id'],
                'indexes': [models.Index(fields=['table', 'group_id'], name='backend_lay_table_i_7ecd6a_idx')],
                'unique_together': {('table', 'group_id')},
            },
        ),
    ]
