# Generated by Django 4.2.27 on 2026-03-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_gislayer_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='otefviewportstate',
            name='viewer_angle_deg',
            field=models.FloatField(default=0.0),
        ),
    ]
