# Generated by Django 4.2.27 on 2026-03-23 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_otefviewportstate_viewer_angle_deg"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurationEditRevision",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("project_name", models.CharField(blank=True, default="", max_length=255)),
                ("submission_id", models.CharField(blank=True, default="", max_length=100)),
                ("feature_id", models.CharField(max_length=100)),
                ("edit_type", models.CharField(default="move_geometry", max_length=50)),
                ("before_geom", models.JSONField(default=dict)),
                ("after_geom", models.JSONField(default=dict)),
                ("edited_by", models.CharField(blank=True, default="", max_length=255)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="curation_edit_revisions",
                        to="backend.table",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="curationeditrevision",
            index=models.Index(
                fields=["table", "feature_id", "-created_at"],
                name="backend_cur_table_i_19a40a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="curationeditrevision",
            index=models.Index(
                fields=["table", "submission_id", "-created_at"],
                name="backend_cur_table_i_76d20d_idx",
            ),
        ),
    ]

