# Generated by Django 4.2.27 on 2026-03-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_curationeditrevision'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='curationeditrevision',
            new_name='backend_cur_table_i_418903_idx',
            old_name='backend_cur_table_i_19a40a_idx',
        ),
        migrations.RenameIndex(
            model_name='curationeditrevision',
            new_name='backend_cur_table_i_975fbb_idx',
            old_name='backend_cur_table_i_76d20d_idx',
        ),
    ]
