# Generated by Django 4.2.27 on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_rename_backend_cur_table_i_19a40a_idx_backend_cur_table_i_418903_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otefviewportstate',
            name='workshop_auto_publish',
            field=models.BooleanField(default=False),
        ),
    ]
