# Generated by Django 4.2.27 on 2026-04-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_otefviewportstate_workshop_auto_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='otefviewportstate',
            name='workshop_autopublish_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
