# Generated by Django 4.2.27 on 2026-04-20 22:06

from django.db import migrations
from django.utils import timezone


def backfill_workshop_autopublish_started_at(apps, schema_editor):
    OTEFViewportState = apps.get_model('backend', 'OTEFViewportState')
    now = timezone.now()
    OTEFViewportState.objects.filter(
        workshop_auto_publish=True,
        workshop_autopublish_started_at__isnull=True,
    ).update(workshop_autopublish_started_at=now)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_otefviewportstate_workshop_autopublish_started_at'),
    ]

    operations = [
        migrations.RunPython(backfill_workshop_autopublish_started_at, noop_reverse),
    ]
