# Generated by Django 4.2.27 on 2026-04-20 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_workshop_autopublish_started_at_backfill'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopAutopublishSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_autopublish_suppressions', to='backend.table')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workshopautopublishsuppression',
            constraint=models.UniqueConstraint(fields=('table', 'submission_id'), name='uniq_workshop_suppression_per_submission'),
        ),
    ]
